/**
 * P4-48: Counterfactual debate mode.
 *
 * Forces an agent to argue the opposite of its original position,
 * then measures how robust the original answer is against the best
 * counter-argument. A high-confidence answer that crumbles under
 * counterfactual pressure indicates fragile reasoning.
 *
 * Usage:
 *   const result = await runCounterfactualDebate(originalOpinion, provider, messages);
 *   // result.robustnessScore — 0 to 1 (1 = original held up perfectly)
 */

import { askProviderStream } from "./providers.js";
import type { Message, Provider } from "./providers.js";
import logger from "./logger.js";

export interface CounterfactualResult {
  /** The original opinion text. */
  originalOpinion: string;
  /** The counterfactual argument generated by the same agent. */
  counterfactualArgument: string;
  /** The agent's rebuttal to the counterfactual. */
  rebuttal: string;
  /** 0–1 score: how well the original opinion survived the counterfactual challenge. */
  robustnessScore: number;
  /** Whether the agent conceded any points. */
  concessions: string[];
}

/**
 * Run a counterfactual debate: force the agent to argue the opposite,
 * then ask it to defend its original position against that argument.
 */
export async function runCounterfactualDebate(
  originalOpinion: string,
  provider: Provider,
  contextMessages: Message[],
): Promise<CounterfactualResult> {
  // Step 1: Ask the agent to generate the strongest counter-argument
  const counterMessages: Message[] = [
    ...contextMessages,
    {
      role: "user",
      content: `You previously argued:\n\n"${originalOpinion.substring(0, 2000)}"\n\nNow argue the OPPOSITE position as strongly as possible. Find the best counter-arguments, evidence against your original position, and logical weaknesses. Be thorough and convincing.`,
    },
  ];

  const counterRes = await askProviderStream(provider, counterMessages, () => {}, false);
  const counterfactualArgument = counterRes.text;

  // Step 2: Ask the agent to defend its original position
  const rebuttalMessages: Message[] = [
    ...contextMessages,
    {
      role: "user",
      content: `Your original position was:\n\n"${originalOpinion.substring(0, 1000)}"\n\nA critic argues:\n\n"${counterfactualArgument.substring(0, 1500)}"\n\nDefend your original position. Where is the critic right? Where are they wrong? Do you concede any points? Rate your confidence in your original answer from 0 to 1.`,
    },
  ];

  const rebuttalRes = await askProviderStream(provider, rebuttalMessages, () => {}, false);
  const rebuttal = rebuttalRes.text;

  // Step 3: Extract robustness score from rebuttal
  const confidenceMatch = rebuttal.match(/(?:confidence|rating|score)[:\s]*([01](?:\.\d+)?)/i);
  // P20-04: NaN guard — parseFloat can return NaN if regex captures non-numeric text
  const _parsedRobustness = confidenceMatch ? parseFloat(confidenceMatch[1]) : 0.5;
  const robustnessScore = Number.isFinite(_parsedRobustness) ? _parsedRobustness : 0.5;

  // Step 4: Extract concessions
  const concessions: string[] = [];
  const concessionPatterns = [
    /(?:I concede|the critic is right|I agree with|fair point|valid criticism)[^.]*\./gi,
  ];
  for (const pattern of concessionPatterns) {
    const matches = rebuttal.match(pattern);
    if (matches) concessions.push(...matches);
  }

  logger.info(
    { robustnessScore, concessionCount: concessions.length },
    "Counterfactual debate completed",
  );

  return {
    originalOpinion: originalOpinion.substring(0, 500),
    counterfactualArgument: counterfactualArgument.substring(0, 1000),
    rebuttal: rebuttal.substring(0, 1000),
    robustnessScore: Math.max(0, Math.min(1, robustnessScore)),
    concessions,
  };
}
