/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        /* All colors reference CSS variables for dual-theme support */
        bg: 'var(--bg)',
        'bg-s1': 'var(--bg-surface-1)',
        'bg-s2': 'var(--bg-surface-2)',
        'bg-s3': 'var(--bg-surface-3)',
        'border-subtle': 'var(--border-subtle)',
        'border-medium': 'var(--border-medium)',
        'text-primary': 'var(--text-primary)',
        'text-secondary': 'var(--text-secondary)',
        'text-muted': 'var(--text-muted)',
        'accent-mint': 'var(--accent-mint)',
        'accent-blue': 'var(--accent-blue)',
        'accent-coral': 'var(--accent-coral)',
        'accent-gold': 'var(--accent-gold)',

        /* Legacy aliases for backward compat during migration */
        surface: 'var(--bg)',
        'surface-lighter': 'var(--bg-s1)',
        text: 'var(--text-primary)',
        'text-dim': 'var(--text-muted)',
        accent: 'var(--accent-mint)',
        danger: 'var(--accent-coral)',
        warning: 'var(--accent-gold)',
        success: 'var(--accent-mint)',
      },
      fontFamily: {
        sans: ['Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        display: ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.375rem',
        'md': '0.625rem',
        'lg': '0.75rem',
        'xl': '1rem',
        '2xl': '1.25rem',
        '3xl': '1.5rem',
        'card': '16px',
        'button': '12px',
        'input': '12px',
        'modal': '24px',
        'pill': '9999px',
      },
      boxShadow: {
        'card': 'var(--card-shadow, 0 4px 24px -12px rgba(0,0,0,0.5))',
        'card-hover': 'var(--card-shadow-hover, 0 8px 32px -8px rgba(0,0,0,0.6))',
        'glow-mint': '0 0 30px -10px var(--accent-mint)',
        'glow-blue': '0 0 30px -10px var(--accent-blue)',
        'glow-coral': '0 0 30px -10px var(--accent-coral)',
        'glow-gold': '0 0 30px -10px var(--accent-gold)',
        'glow-sm': '0 0 15px -5px rgba(110, 231, 183, 0.15)',
        'glow': '0 0 30px -10px rgba(110, 231, 183, 0.2)',
        'glow-lg': '0 0 60px -15px rgba(110, 231, 183, 0.25)',
        'inner-glow': 'inset 0 0 20px -8px rgba(110, 231, 183, 0.1)',
        'glass': '0 4px 24px -12px rgba(0, 0, 0, 0.5), inset 0 1px 0 rgba(255, 255, 255, 0.04)',
      },
      spacing: {
        '18': '4.5rem',
        '88': '22rem',
        '120': '30rem',
      },
      animation: {
        'shimmer': 'shimmer 2s linear infinite',
        'float': 'float 6s ease-in-out infinite',
        'glow-pulse': 'glow-pulse 3s ease-in-out infinite',
        'slide-up': 'slide-up 0.4s ease-out',
        'fade-in': 'fade-in 0.3s ease-out',
        'drift': 'drift 20s ease-in-out infinite',
        'drift-slow': 'drift 30s ease-in-out infinite',
        'spin-slow': 'spin 8s linear infinite',
      },
      keyframes: {
        shimmer: {
          '0%': { backgroundPosition: '-200% center' },
          '100%': { backgroundPosition: '200% center' },
        },
        float: {
          '0%, 100%': { transform: 'translateY(0px)' },
          '50%': { transform: 'translateY(-8px)' },
        },
        'glow-pulse': {
          '0%, 100%': { opacity: '0.4', filter: 'blur(40px)' },
          '50%': { opacity: '0.7', filter: 'blur(50px)' },
        },
        'slide-up': {
          '0%': { opacity: '0', transform: 'translateY(12px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
        'fade-in': {
          '0%': { opacity: '0' },
          '100%': { opacity: '1' },
        },
        drift: {
          '0%, 100%': { transform: 'translate(0, 0)' },
          '25%': { transform: 'translate(30px, -20px)' },
          '50%': { transform: 'translate(-20px, 15px)' },
          '75%': { transform: 'translate(15px, 25px)' },
        },
      },
      backgroundImage: {
        'gradient-radial': 'radial-gradient(var(--tw-gradient-stops))',
        'gradient-mint': 'linear-gradient(135deg, var(--accent-mint) 0%, #34d399 100%)',
        'gradient-blue': 'linear-gradient(135deg, var(--accent-blue) 0%, #60a5fa 100%)',
        'gradient-coral': 'linear-gradient(135deg, var(--accent-coral) 0%, #f87171 100%)',
        'gradient-gold': 'linear-gradient(135deg, var(--accent-gold) 0%, #fbbf24 100%)',
      },
      fontSize: {
        'display': ['3.5rem', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '800' }],
        'hero': ['3rem', { lineHeight: '1.15', letterSpacing: '-0.02em', fontWeight: '700' }],
      },
    },
  },
  plugins: [],
}
