// Generated by React Router

import "react-router"

declare module "react-router" {
  interface Register {
    pages: Pages
    routeFiles: RouteFiles
    routeModules: RouteModules
  }
}

type Pages = {
  "/": {
    params: {};
  };
  "/login": {
    params: {};
  };
  "/register": {
    params: {};
  };
  "/dashboard": {
    params: {};
  };
  "/chat": {
    params: {};
  };
  "/projects": {
    params: {};
  };
};

type RouteFiles = {
  "root.tsx": {
    id: "root";
    page: "/" | "/login" | "/register" | "/dashboard" | "/chat" | "/projects";
  };
  "routes/home.tsx": {
    id: "routes/home";
    page: "/";
  };
  "routes/login.tsx": {
    id: "routes/login";
    page: "/login";
  };
  "routes/register.tsx": {
    id: "routes/register";
    page: "/register";
  };
  "components/layout/AppLayout.tsx": {
    id: "components/layout/AppLayout";
    page: "/dashboard" | "/chat" | "/projects";
  };
  "routes/dashboard.tsx": {
    id: "routes/dashboard";
    page: "/dashboard";
  };
  "routes/chat.tsx": {
    id: "routes/chat";
    page: "/chat";
  };
  "routes/projects.tsx": {
    id: "routes/projects";
    page: "/projects";
  };
};

type RouteModules = {
  "root": typeof import("./app/root.tsx");
  "routes/home": typeof import("./app/routes/home.tsx");
  "routes/login": typeof import("./app/routes/login.tsx");
  "routes/register": typeof import("./app/routes/register.tsx");
  "components/layout/AppLayout": typeof import("./app/components/layout/AppLayout.tsx");
  "routes/dashboard": typeof import("./app/routes/dashboard.tsx");
  "routes/chat": typeof import("./app/routes/chat.tsx");
  "routes/projects": typeof import("./app/routes/projects.tsx");
};