import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
  index("routes/home.tsx"),
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  route("chat", "routes/chat.tsx"),
  route("chat/:id", "routes/chat-detail.tsx"),
  route("api/deliberate", "routes/api.deliberate.tsx"),
  route("api/evaluate", "routes/api.evaluate.tsx"),
  route("settings", "routes/settings.tsx"),
  route("profile", "routes/profile.tsx"),
  route("language-models", "routes/language-models.tsx"),
  route("workflows", "routes/workflows.tsx"),
  route("prompts", "routes/prompts.tsx"),
  route("knowledge-bases", "routes/knowledge-bases.tsx"),
  route("marketplace", "routes/marketplace.tsx"),
  route("archetypes", "routes/archetypes.tsx"),
  route("memory", "routes/memory.tsx"),
  route("skills", "routes/skills.tsx"),
  route("repos", "routes/repos.tsx"),
  route("evaluation", "routes/evaluation.tsx"),
  route("projects", "routes/projects.tsx"),
  route("admin/users", "routes/admin-users.tsx"),
  route("admin/analytics", "routes/admin-analytics.tsx"),
  route("admin/system", "routes/admin-system.tsx"),
  route("admin/audit", "routes/admin-audit.tsx"),
] satisfies RouteConfig;
