import { type RouteConfig, index, layout, route } from "@react-router/dev/routes";

export default [
  // Marketing pages — wrapped with Navbar + Footer
  layout("routes/marketing-layout.tsx", [
    index("routes/landing.tsx"),
    route("pricing", "routes/pricing.tsx"),
    route("about", "routes/about.tsx"),
    route("blog", "routes/blog.tsx"),
    route("careers", "routes/careers.tsx"),
    route("contact", "routes/contact.tsx"),
    route("llm-leaderboard", "routes/llm-leaderboard.tsx"),
    route("infra-calculator", "routes/infra-calculator.tsx"),
    route("status", "routes/status.tsx"),
    route("product/council", "routes/product.council.tsx"),
    route("product/knowledge", "routes/product.knowledge.tsx"),
    route("product/workflows", "routes/product.workflows.tsx"),
    route("product/archetypes", "routes/product.archetypes.tsx"),
    route("product/connectors", "routes/product.connectors.tsx"),
    route("product/developer-platform", "routes/product.developer-platform.tsx"),
    route("product/deliberation-modes", "routes/product.deliberation-modes.tsx"),
    route("product/desktop-app", "routes/product.desktop-app.tsx"),
  ]),
  // Auth pages (no navbar)
  route("login", "routes/login.tsx"),
  route("register", "routes/register.tsx"),
  // App pages (sidebar layout handled by root.tsx)
  route("dashboard", "routes/home.tsx"),
  route("chat", "routes/chat.tsx"),
  route("chat/:id", "routes/chat-detail.tsx"),
  route("api/deliberate", "routes/api.deliberate.tsx"),
  route("api/evaluate", "routes/api.evaluate.tsx"),
  route("settings", "routes/settings.tsx"),
  route("profile", "routes/profile.tsx"),
  route("language-models", "routes/language-models.tsx"),
  route("workflows", "routes/workflows.tsx"),
  route("prompts", "routes/prompts.tsx"),
  route("knowledge-bases", "routes/knowledge-bases.tsx"),
  route("marketplace", "routes/marketplace.tsx"),
  route("archetypes", "routes/archetypes.tsx"),
  route("memory", "routes/memory.tsx"),
  route("skills", "routes/skills.tsx"),
  route("repos", "routes/repos.tsx"),
  route("evaluation", "routes/evaluation.tsx"),
  route("projects", "routes/projects.tsx"),
  route("build", "routes/build.tsx"),
  route("admin/users", "routes/admin-users.tsx"),
  route("admin/analytics", "routes/admin-analytics.tsx"),
  route("admin/system", "routes/admin-system.tsx"),
  route("admin/audit", "routes/admin-audit.tsx"),
] satisfies RouteConfig;
