apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "aibyai.fullname" . }}-config
  labels:
    {{- include "aibyai.labels" . | nindent 4 }}
data:
  NODE_ENV: "production"
  PORT: {{ .Values.backend.port | quote }}
  {{- range $key, $value := .Values.env }}
  {{ $key }}: {{ $value | quote }}
  {{- end }}
