apiVersion: v1
kind: Service
metadata:
  name: aibyai-backend
  namespace: aibyai
  labels:
    app: aibyai-backend
    app.kubernetes.io/component: backend
spec:
  type: ClusterIP
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: aibyai-backend
